joint_state_broadcaster:
  ros__parameters:
    joint_feedback_rate: 100
    joint_axes: [0, 1, 2, 3]
    joint_name: ["axis_x", "axis_y", "axis_z", "axis_r"]
    encoder_joint_topic: /joint_states
    isaacsim_joint_topic: /joint_command
    gazebo_joint_topic: /gazebo_position_controller/commands

joint_trajectory_controller:
  ros__parameters:
    joint_axes: [0, 1, 2]
    joint_trajectory_action: /movensys_cartesian_controller/follow_joint_trajectory
    wmx_param_file_path: ""
